name: MHB
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
languages: ["en", "fr"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: en
languageNames:
  fr: French
  en: English
